// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;

/**
 *
 */
public class Feeder extends SubsystemBase {
    private WPI_TalonFX m_feederMotor;

    // Feeder subsystem
    public Feeder() {
        m_feederMotor = new WPI_TalonFX(6);

        m_feederMotor.clearStickyFaults();
        m_feederMotor.configFactoryDefault();
        m_feederMotor.setInverted(false);
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putNumber("Feeder Current Percentage", m_feederMotor.getMotorOutputPercent());
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation
    }

    // Turns the feeder on to 25%
    public void feederOn() {
        m_feederMotor.set(ControlMode.PercentOutput, 0.25d);
    }

    // Turns the feeder off
    public void feederOff() {
        stop();
    }

    public void stop() {
        m_feederMotor.set(ControlMode.Current, 0);
    }
}
