// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Drivetrain;
import frc.robot.subsystems.Targeting;

/**
 *
 */
public class LocateTarget extends CommandBase 
{
    private final Drivetrain m_drivetrain;
    private final Targeting m_targeting;
    
    public LocateTarget(Drivetrain drivetrain, Targeting targeting) {
        m_drivetrain = drivetrain;
        addRequirements(m_drivetrain);
        m_targeting = targeting;
        addRequirements(m_targeting); // Is this needed?
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() 
    {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() 
    {
        //Turn on the LED
        m_targeting.controlLight(true);

		//Get velocity data from targeting
        double percentOutput = m_targeting.navToTarget();

        //Send velocity data to vision drive
        m_drivetrain.percentDrive(-percentOutput, percentOutput);
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) 
    {
        //Turn off the LED
        m_targeting.controlLight(false);
    	
        //Reset the PID for the next run
        m_targeting.resetPID();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() 
    {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() 
    {
        return false;
    }
}
