// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Drivetrain;

/**
 *
 */
public class TankDrive extends CommandBase {
    private final Drivetrain m_drivetrain;
    private final XboxController m_xboxcontroller;

    public TankDrive(Drivetrain subsystem, XboxController xboxcontroller) {
        m_drivetrain = subsystem;
        addRequirements(m_drivetrain);
        m_xboxcontroller = xboxcontroller;
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        double leftJoy = m_xboxcontroller.getLeftY();
        double rightJoy = m_xboxcontroller.getRightX();
        
       m_drivetrain.percentDrive(leftJoy, rightJoy);
    }
}


